### ISSUE TITLE
ES6 import

### ISSUE THREAD

**Issue by petertenhoor** [snorpey/triangulate-image#53]
Hi there, I'm trying to use this package in my ES6 React project. The package was installed successfully to my node_modules. I have tried to import it using ES6 import:

`import triangulate from "triangulate-image";`

Which gives the error:

`Uncaught Error: Cannot find module "triangulate-image"`

Is this package currently not compatible with ES6?

**Comment by snorpey** [comment]
hey @petertenhoor thank you for your interest in this project!

this library should support es6 imports. since this library supports running on node as well as in the browser, it is using the `module` field in [`package.json`](https://github.com/snorpey/triangulate-image/blob/master/package.json#L10) to indicate the path for the ES6 module file.

if you're using a module bundler like webpack, please make sure it is configured support the `module` field.

any chance you could share an example setup of the project for me to look at? i'm mostly interested in the way the project is set up and how exactly the library is imported.

thanks again for your interest and for taking the time to file a report!

**Comment by petertenhoor** [comment]
False alarm. I got it working with require at first and after a fresh npm install also with ES6 import, so it had to be something on my side.
